import { VoiceMemo } from '../types';
import { formatRelativeTime } from './index';

export const formatMemoForExport = (memo: VoiceMemo): string => {
  const date = new Date(memo.createdAt).toLocaleDateString(undefined, {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  
  const time = new Date(memo.createdAt).toLocaleTimeString(undefined, {
    hour: '2-digit',
    minute: '2-digit',
  });

  let exportText = `# ${memo.title || 'Voice Memo'}\n`;
  exportText += `Date: ${date} at ${time}\n`;
  exportText += `Category: ${memo.category}\n\n`;

  if (memo.aiAnalysis) {
    exportText += `## Summary\n${memo.aiAnalysis.summary}\n\n`;

    if (memo.aiAnalysis.actionItems && memo.aiAnalysis.actionItems.length > 0) {
      exportText += `## Action Items\n`;
      memo.aiAnalysis.actionItems.forEach(item => {
        exportText += `- [ ] ${item}\n`;
      });
      exportText += `\n`;
    }

    if (memo.aiAnalysis.keywords && memo.aiAnalysis.keywords.length > 0) {
      exportText += `Keywords: ${memo.aiAnalysis.keywords.join(', ')}\n\n`;
    }
  }

  exportText += `## Transcript\n${memo.transcription}\n`;
  
  exportText += `\n---\nGenerated by MemoVox AI`;

  return exportText;
};
